services:
  - type: web
    name: projectpair-backend
    runtime: node
    rootDir: project-pair-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
